import { ConnectButton } from "@rainbow-me/rainbowkit";
import { useSwitchChain, useSendTransaction, useChainId } from "wagmi";
import { parseEther } from "viem";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useEffect } from "react";

const Home: NextPage = () => {
  const { chains, switchChain } = useSwitchChain();
  const { sendTransaction } = useSendTransaction();
  const chainId = useChainId();

  const handleSwitchChain = () => {
    switchChain({
      chainId: 42161,
    });
  };

  useEffect(() => {
    console.log('chainId', chainId);
  }, [chainId]);

  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />
        <button onClick={handleSwitchChain}>Switch Chain</button>
        <button
          onClick={() =>
            sendTransaction({
              to: "0xd2135CfB216b74109775236E36d4b433F1DF507B",
              chainId: 42161,
              value: parseEther("0"),
            })
          }
        >
          Send transaction
        </button>
      </main>
    </div>
  );
};

export default Home;
